/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-06-20 15:30:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.matching;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class matching_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/matching/../include/footer.jsp", Long.valueOf(1592337320819L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1590910150530L));
    _jspx_dependants.put("/WEB-INF/views/matching/../include/top.jsp", Long.valueOf(1592666138436L));
    _jspx_dependants.put("jar:file:/D:/git/TEUCHING/TeuChingTeuChing/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=EB+Garamond:400,400i,500,500i,600,600i,700,700i&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"../resources/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/aos.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/ionicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/jquery.timepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/matching/matching.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".toggle_radio{\r\n");
      out.write("  background: #ffb5b5;\r\n");
      out.write("  margin: 4px auto;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  padding: 0 !important;\r\n");
      out.write("  -webkit-border-radius: 50px;\r\n");
      out.write("  -moz-border-radius: 50px;\r\n");
      out.write("  border-radius: 50px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  height: 26px;\r\n");
      out.write("  width: 215px;\r\n");
      out.write("  padding-left: 10%;\r\n");
      out.write("}\r\n");
      out.write(".toggle_radio > * {\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write(".toggle_radio input[type=radio]{\r\n");
      out.write("  display: none;\r\n");
      out.write("  /*position: fixed;*/\r\n");
      out.write("}\r\n");
      out.write(".toggle_radio label{\r\n");
      out.write("  font: 90%/1.618 \"Source Sans Pro\";\r\n");
      out.write("  color: rgba(255,255,255,.9);\r\n");
      out.write("  z-index: 0;\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 100px;\r\n");
      out.write("  height: 20px;\r\n");
      out.write("  margin: 3px 3px;\r\n");
      out.write("  -webkit-border-radius: 50px;\r\n");
      out.write("  -moz-border-radius: 50px;\r\n");
      out.write("  border-radius: 50px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  /*background: rgba(0,0,0,.1);*/\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  /*margin: 0 2px;*/\r\n");
      out.write("  /*background: blue;*/ /*make it blue*/\r\n");
      out.write("}\r\n");
      out.write(".toggle_option_slider{\r\n");
      out.write("  /*display: none;*/\r\n");
      out.write("  /*background: red;*/\r\n");
      out.write("  width: 100px;\r\n");
      out.write("  height: 20px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 3px;\r\n");
      out.write("  -webkit-border-radius: 50px;\r\n");
      out.write("  -moz-border-radius: 50px;\r\n");
      out.write("  border-radius: 50px;\r\n");
      out.write("  -webkit-transition: all .4s ease;\r\n");
      out.write("  -moz-transition: all .4s ease;\r\n");
      out.write("  -o-transition: all .4s ease;\r\n");
      out.write("  -ms-transition: all .4s ease;\r\n");
      out.write("  transition: all .4s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#first_toggle:checked ~ .toggle_option_slider{\r\n");
      out.write("  background: rgba(255,255,255,.3);\r\n");
      out.write("  left: 3px;\r\n");
      out.write("}\r\n");
      out.write("#second_toggle:checked ~ .toggle_option_slider{\r\n");
      out.write("  background: rgba(255,255,255,.3);\r\n");
      out.write("  left: 109px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title{\r\n");
      out.write("\tpadding-left: 32%;\r\n");
      out.write("\t color: #695f5f;\r\n");
      out.write("}\r\n");
      out.write("#Jointitle{\r\n");
      out.write("\tpadding-left: 19%;\r\n");
      out.write("\tfont-size:1.2vw;\r\n");
      out.write("\t color: #695f5f;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#atag{\r\n");
      out.write("\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("}\r\n");
      out.write("#headerTitle{\r\n");
      out.write("\tpadding-left: 0%;\r\n");
      out.write("\tfont-size:1.2vw;\r\n");
      out.write("\t color: #695f5f;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand{\r\n");
      out.write("\t font-size: 40px !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<header\r\n");
      out.write("\tclass=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\"\r\n");
      out.write("\tid=\"ftco-navbar\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row m-auto\">\r\n");
      out.write("\t\t\t<div class=\"col-12 w-100 text-center\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand w-100\" href=\"/teuching/index/index.do\">TeuChing</a>\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#ftco-nav\" aria-controls=\"ftco-nav\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t\t<span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-12 w-100 text-center\">\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav m-auto\">\r\n");
      out.write("\t\t\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /WEB-INF/views/matching/../include/top.jsp(112,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t");
            //  c:if
            org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
            boolean _jspx_th_c_005fif_005f1_reused = false;
            try {
              _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
              // /WEB-INF/views/matching/../include/top.jsp(113,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberType eq 'member'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
              if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item active\"><a\r\n");
                  out.write("\t\t\t\t\t\t\t\t\thref=\"");
                  out.print(request.getContextPath());
                  out.write("/member/mypage_M.do\"\r\n");
                  out.write("\t\t\t\t\t\t\t\t\tclass=\"nav-link\">MyPage</a></li>\r\n");
                  out.write("\t\t\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
              _jspx_th_c_005fif_005f1_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t");
            //  c:if
            org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
            boolean _jspx_th_c_005fif_005f2_reused = false;
            try {
              _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
              // /WEB-INF/views/matching/../include/top.jsp(118,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberType eq 'trainer'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
              if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item active\"><a\r\n");
                  out.write("\t\t\t\t\t\t\t\t\thref=\"");
                  out.print(request.getContextPath());
                  out.write("/member/mypage_T.do\"\r\n");
                  out.write("\t\t\t\t\t\t\t\t\tclass=\"nav-link\">MyPage</a></li>\r\n");
                  out.write("\t\t\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
              _jspx_th_c_005fif_005f2_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t");
            //  c:if
            org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
            boolean _jspx_th_c_005fif_005f3_reused = false;
            try {
              _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
              // /WEB-INF/views/matching/../include/top.jsp(123,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberType eq 'manager'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
              if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item active\"><a\r\n");
                  out.write("\t\t\t\t\t\t\t\t\thref=\"");
                  out.print(request.getContextPath());
                  out.write("/manager/report.do\"\r\n");
                  out.write("\t\t\t\t\t\t\t\t\tclass=\"nav-link\">Manager</a></li>\r\n");
                  out.write("\t\t\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
              _jspx_th_c_005fif_005f3_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item active\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/index/aboutus.do\" class=\"nav-link\">AboutUs</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item active\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/matching/main.do\" class=\"nav-link\">Matching</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item active\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/notice/notice.do?start=1&end=5\" class=\"nav-link\">Notice</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"topWrapper\" id=\"topWrapper\"\r\n");
      out.write("\t\t\tstyle=\"position: absolute; top: 1vw; right: 1vw;\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f5_reused = false;
      try {
        _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f5.setParent(null);
        // /WEB-INF/views/matching/../include/top.jsp(152,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
        if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t<div class=\"topLogOut\">\r\n");
            out.write("\t\t\t\t");
            //  c:if
            org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
            boolean _jspx_th_c_005fif_005f6_reused = false;
            try {
              _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f5);
              // /WEB-INF/views/matching/../include/top.jsp(154,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberType eq 'member'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
              if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t<a style=\"color:black\" href=\"");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("/message/msgboxrecv.do\">✉</a>\r\n");
                  out.write("\t\t\t\t\t<a onclick=\"location= 'detail.cs?id=");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write('"');
                  out.write('>');
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("\t님  환영합니다. </a>\r\n");
                  out.write("\t\t\t\t\t<a href =\"");
                  out.print(request.getContextPath());
                  out.write("/member/mypage_M.do\"> /  myPage</a>\r\n");
                  out.write("\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
              _jspx_th_c_005fif_005f6_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t");
            if (_jspx_meth_c_005fif_005f7(_jspx_th_c_005fif_005f5, _jspx_page_context))
              return;
            out.write("\t\r\n");
            out.write("\t\t\t\t\t\t<!-- <a>MyPage</a>  -->\r\n");
            out.write("\t\t\t\t\t\t<a href=\"");
            out.print(request.getContextPath());
            out.write("/member/logout.do\">/  logout</a>\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
        _jspx_th_c_005fif_005f5_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인모달  -->\r\n");
      out.write("<div class=\"modal fade\" id=\"loginModal\" tabindex=\"-1\" role=\"dialog\" >\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("        <!-- 닫기버튼 -->\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <form class=\"form-signin\" action=\"");
      out.print(request.getContextPath());
      out.write("/member/loginImple.do\">\r\n");
      out.write("            <h2 id=\"title\">Please sign in</h2>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 offset-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"toggle_radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"toggle_option\" id=\"first_toggle\"\tname=\"account\" value=\"member\"checked> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"toggle_option\" id=\"second_toggle\" name=\"account\" value=\"trainer\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t <label for=\"first_toggle\"><p>Member</p></label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"second_toggle\"><p>Trainer</p></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"toggle_option_slider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("            \r\n");
      out.write("            <label for=\"userEmail\" class=\"sr-only\">Email address</label>\r\n");
      out.write("            <input type=\"text\" id=\"email\" name=\"email\" class=\"form-control\" placeholder=\"Email address\" required autofocus>\r\n");
      out.write("            <label for=\"userPwd\" class=\"sr-only\">Password</label>\r\n");
      out.write("            <input type=\"password\" name=\"password\" id=\"password\" class=\"form-control\" placeholder=\"Password\" required>\r\n");
      out.write("            <div class=\"warning\"></div>\r\n");
      out.write("            <button class=\"btn btn-lg btn-primary btn-block\" id=\"btnLogin\" type=\"submit\">로그인</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <a type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</a>\r\n");
      out.write("        <a type=\"button\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/find_pw_form.do\" class=\"btn btn-primary\"> 비밀번호 찾기 </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 가입모달 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"joinModal\" tabindex=\"-1\" role=\"dialog\" >\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("      \t<h3 id=\"headerTitle\">Welcome Teu-Ching!</h3>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("        <!-- 닫기버튼 -->\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <p id=\"Jointitle\">만나서 반갑습니다! <br>가입하실 유형을 선택해주세요.</p>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 offset-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"toggle_radio\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"first_toggle\"><a id=\"atag\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/mjoin.do?data=member\">Member</a></label> \r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"second_toggle\"><a id=\"atag\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/mjoin.do?data=trainer\"> Trainer</a></label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <a type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write(" <script src=\"../resources/js/account/login.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<input type=\"hidden\" id=\"memberType\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t<header id=\"header\" class=\"ftco-section\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"searchWordWrapper\">\r\n");
      out.write("\t\t\t\t<div style=\"margin-left: 35px;\">\r\n");
      out.write("\t\t\t\t\t<select id=\"searchOption\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"trainer\">트레이너</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"post\">게시판</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"keywordInput\" class=\"form-control\" placeholder=\"검색어를 입력하세요.\">\r\n");
      out.write("\t\t\t\t\t\t<button id=\"inputBtn\" class=\"icon-search\"></button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<a href=\"#header\" id=\"topUp\">\r\n");
      out.write("\t\t<img style=\"width: 52px;\" src=\"../resources/img/topUp.png\">\r\n");
      out.write("\t</a>\r\n");
      out.write("\t<section class=\"container\" style=\"width: 840px;\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<table class=\"keywordSearchTable\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"searchTableTh\">운동목적</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"searchTableTd\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"purpose\" value=\"체형교정\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"purpose\" value=\"건강증진\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"purpose\" value=\"다이어트\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"purpose\" value=\"바디프로필\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"purpose\" value=\"취미\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"purpose\" value=\"대회준비\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"purpose\" value=\"재활치료\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"purpose\" value=\"벌크업\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"purpose\" value=\"기초체력\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"purpose\" value=\"시험준비\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"searchTableTh\">운동종목</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"searchTableTd\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"sports\" value=\"요가\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"sports\" value=\"필라테스\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"sports\" value=\"스피닝\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"sports\" value=\"헬스\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"sports\" value=\"크로스핏\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"sports\" value=\"수영\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"sports\" value=\"기타\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"searchTableTh\">지역</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"searchTableTd\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" id=\"registration\" name=\"area\" value=\"등록지 기준\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"memberArea\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"area\" value=\"타지역\">\r\n");
      out.write("\t\t\t\t\t\t<select id=\"placeSelect\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"서울\">서울</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"세종\">세종</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"부산\">부산</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"대구\">대구</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"인천\">인천</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"광주\">광주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"대전\">대전</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"울산\">울산</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"제주\">제주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"서귀포\">서귀포</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"수원\">수원</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"고양\">고양</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"성남\">성남</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"용인\">용인</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"부천\">부천</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"안산\">안산</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"남양주\">남양주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"안양\">안양</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"화성\">화성</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"평택\">평택</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"의정부\">의정부</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"시흥\">시흥</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"파주\">파주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"김포\">김포</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"광명\">광명</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"광주\">광주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"군포\">군포</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"오산\">오산</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"이천\">이천</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"양주\">양주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"안성\">안성</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"구리\">구리</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"포천\">포천</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"의왕\">의왕</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"하남\">하남</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"여주\">여주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"동두천\">동두천</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"과천\">과천</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"춘천\">춘천</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"원주\">원주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"강릉\">강릉</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"동해\">동해</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"태백\">태백</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"속초\">속초</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"삼척\">삼척</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"청주\">청주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"충주\">충주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"제천\">제천</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"천안\">천안</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"공주\">공주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"보령\">보령</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"아산\">아산</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"서산\">서산</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"논산\">논산</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"계룡\">계룡</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"전주\">전주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"군산\">군산</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"익산\">익산</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"정읍\">정읍</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"남원\">남원</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"김제\">김제</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"목포\">목포</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"여수\">여수</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"순천\">순천</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"나주\">나주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"광양\">광양</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"포항\">포항</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"경주\">경주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"김천\">김천</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"안동\">안동</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"구미\">구미</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"영주\">영주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"영천\">영천</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"상주\">상주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"문경\">문경</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"경산\">경산</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"창원\">창원</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"전주\">전주</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"통영\">통영</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"사천\">사천</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"김해\">김해</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"밀양\">밀양</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"거제\">거제</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"양산\">양산</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"searchTableTh\">수업 인원</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"searchTableTd\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"classSize\" value=\"1:1\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"classSize\" value=\"N:1\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"searchTableTh\">성별</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"searchTableTd\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"gender\" value=\"남\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"gender\" value=\"여\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"searchTableTh\">장소</th>\r\n");
      out.write("\t\t\t\t\t<td class=\"searchTableTd\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"place\" value=\"INDOOR EXERCIES\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"keywordBtn\" name=\"place\" value=\"OUTDOOR EXERCIES\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<button id=\"keywordSearchBtn\">Search</button>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<section class=\"container\" style=\"margin-top: 13%; margin-bottom: 10%;\">\r\n");
      out.write("\t\t<table id=\"postTable\" style=\"margin-left: auto; margin-right: auto;\">\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<footer class=\"ftco-footer ftco-section bg-light\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row d-flex\">\r\n");
      out.write("\t\t\t<div class=\"col-md\">\r\n");
      out.write("\t\t\t\t<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"ftco-heading-2\">Meditative</h2>\r\n");
      out.write("\t\t\t\t\t<p>Far far away, behind the word mountains, far from the\r\n");
      out.write("\t\t\t\t\t\tcountries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("\t\t\t\t\t<ul class=\"ftco-footer-social list-unstyled float-lft mt-3\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-twitter\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-facebook\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-instagram\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md\">\r\n");
      out.write("\t\t\t\t<div class=\"ftco-footer-widget mb-4 ml-md-4\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"ftco-heading-2\">Popular Links</h2>\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/teuching/matching/main.do\">Matching</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md\">\r\n");
      out.write("\t\t\t\t<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"ftco-heading-2\">Quick Links</h2>\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/index/index.do\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/index/aboutus.do\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/notice/notice.do?start=1&end=5\">Notice</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md\">\r\n");
      out.write("\t\t\t\t<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"ftco-heading-2\">Have a Questions?</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"block-23 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"icon icon-map-marker\"></span><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text\">6 Teheran-ro 14-gil, Gangnam-gu, Seoul</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"icon icon-phone\"></span><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"text\">1544-9970</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"text\">teuching.official@gmail.com</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p class=\"mb-0\">\r\n");
      out.write("\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\t\t\t\t\tCopyright &copy;\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\tdocument.write(new Date().getFullYear());\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\tAll rights reserved | This template is made with <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-heart\" aria-hidden=\"true\"></i> by <a\r\n");
      out.write("\t\t\t\t\t\thref=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"ftco-loader\" class=\"show fullscreen\">\r\n");
      out.write("\t\t<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("\t\t\t<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("\t\t\t\tstroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("\t\t\t<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("\t\t\t\tstroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\t<script src=\"../resources/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/aos.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/scrollax.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/main.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/matching/matching.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/matching/../include/top.jsp(145,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<!-- 로그인  -->\r\n");
          out.write("\t\t\t\t<div class=\"topLogin\">\r\n");
          out.write("\t\t\t\t\t<a id=\"btnModal\" href=\"#\">Login / </a>\r\n");
          out.write("\t\t\t\t\t <a id=\"btnJModal\" href=\"#\"> Join</a>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f5);
      // /WEB-INF/views/matching/../include/top.jsp(159,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberType eq 'trainer'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<a style=\"color:black\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/profile/reviewforTR.do?trainerEmail=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.tr_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">🇲🇵</a>\r\n");
          out.write("\t\t\t\t\t<a style=\"color:black\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/message/msgboxrecv.do\">✉</a>\r\n");
          out.write("\t\t\t\t\t<a onclick=\"location= 'detail.cs?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.trainerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.trainerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\t님  환영합니다. </a>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f8_reused = false;
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent(null);
      // /WEB-INF/views/matching/matching.jsp(199,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberType == 'trainer'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<button id=\"writeBtn\">Write</button>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      _jspx_th_c_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
    }
    return false;
  }
}
