/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-06-20 16:22:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.profile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class schedule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/profile/../include/top.jsp", Long.valueOf(1592666138436L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1590910150530L));
    _jspx_dependants.put("/WEB-INF/views/profile/../include/footer.jsp", Long.valueOf(1592337320819L));
    _jspx_dependants.put("jar:file:/D:/git/TEUCHING/TeuChingTeuChing/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Teu-Ching Teu-Ching</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#current-year-month{\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size : 17px;\r\n");
      out.write("\tcolor : #ffb5b5;\r\n");
      out.write("\tfont-family: 'Nanum Pen Script', cursive;\r\n");
      out.write("\tfont-family: 'Nunito', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td p{\r\n");
      out.write("\tmargin-top: -22px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor:#ffb5b5;\r\n");
      out.write("\tfont-family: 'Nanum Pen Script', cursive;\r\n");
      out.write("font-family: 'Nunito', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td a{\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\ttransform: translateX(25%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sctitle {\r\n");
      out.write("\tcolor:#ffb5b5;\r\n");
      out.write("\tfont-family: 'Nanum Pen Script', cursive;\r\n");
      out.write("\tfont-size:1.3vw;\r\n");
      out.write("\tpadding-left: -8%;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("#noclick{\r\n");
      out.write("\tcolor : red;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&family=Nunito:ital,wght@1,600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&family=Nunito:ital,wght@1,600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=EB+Garamond:400,400i,500,500i,600,600i,700,700i&display=swap\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"../resources/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/aos.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".toggle_radio{\r\n");
      out.write("  background: #ffb5b5;\r\n");
      out.write("  margin: 4px auto;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  padding: 0 !important;\r\n");
      out.write("  -webkit-border-radius: 50px;\r\n");
      out.write("  -moz-border-radius: 50px;\r\n");
      out.write("  border-radius: 50px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  height: 26px;\r\n");
      out.write("  width: 215px;\r\n");
      out.write("  padding-left: 10%;\r\n");
      out.write("}\r\n");
      out.write(".toggle_radio > * {\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write(".toggle_radio input[type=radio]{\r\n");
      out.write("  display: none;\r\n");
      out.write("  /*position: fixed;*/\r\n");
      out.write("}\r\n");
      out.write(".toggle_radio label{\r\n");
      out.write("  font: 90%/1.618 \"Source Sans Pro\";\r\n");
      out.write("  color: rgba(255,255,255,.9);\r\n");
      out.write("  z-index: 0;\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 100px;\r\n");
      out.write("  height: 20px;\r\n");
      out.write("  margin: 3px 3px;\r\n");
      out.write("  -webkit-border-radius: 50px;\r\n");
      out.write("  -moz-border-radius: 50px;\r\n");
      out.write("  border-radius: 50px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  /*background: rgba(0,0,0,.1);*/\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  /*margin: 0 2px;*/\r\n");
      out.write("  /*background: blue;*/ /*make it blue*/\r\n");
      out.write("}\r\n");
      out.write(".toggle_option_slider{\r\n");
      out.write("  /*display: none;*/\r\n");
      out.write("  /*background: red;*/\r\n");
      out.write("  width: 100px;\r\n");
      out.write("  height: 20px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 3px;\r\n");
      out.write("  -webkit-border-radius: 50px;\r\n");
      out.write("  -moz-border-radius: 50px;\r\n");
      out.write("  border-radius: 50px;\r\n");
      out.write("  -webkit-transition: all .4s ease;\r\n");
      out.write("  -moz-transition: all .4s ease;\r\n");
      out.write("  -o-transition: all .4s ease;\r\n");
      out.write("  -ms-transition: all .4s ease;\r\n");
      out.write("  transition: all .4s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#first_toggle:checked ~ .toggle_option_slider{\r\n");
      out.write("  background: rgba(255,255,255,.3);\r\n");
      out.write("  left: 3px;\r\n");
      out.write("}\r\n");
      out.write("#second_toggle:checked ~ .toggle_option_slider{\r\n");
      out.write("  background: rgba(255,255,255,.3);\r\n");
      out.write("  left: 109px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title{\r\n");
      out.write("\tpadding-left: 32%;\r\n");
      out.write("\t color: #695f5f;\r\n");
      out.write("}\r\n");
      out.write("#Jointitle{\r\n");
      out.write("\tpadding-left: 19%;\r\n");
      out.write("\tfont-size:1.2vw;\r\n");
      out.write("\t color: #695f5f;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#atag{\r\n");
      out.write("\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("}\r\n");
      out.write("#headerTitle{\r\n");
      out.write("\tpadding-left: 0%;\r\n");
      out.write("\tfont-size:1.2vw;\r\n");
      out.write("\t color: #695f5f;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand{\r\n");
      out.write("\t font-size: 40px !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<header\r\n");
      out.write("\tclass=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\"\r\n");
      out.write("\tid=\"ftco-navbar\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row m-auto\">\r\n");
      out.write("\t\t\t<div class=\"col-12 w-100 text-center\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand w-100\" href=\"/teuching/index/index.do\">TeuChing</a>\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#ftco-nav\" aria-controls=\"ftco-nav\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t\t<span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-12 w-100 text-center\">\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav m-auto\">\r\n");
      out.write("\t\t\t\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /WEB-INF/views/profile/../include/top.jsp(112,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t");
            //  c:if
            org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
            boolean _jspx_th_c_005fif_005f1_reused = false;
            try {
              _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
              // /WEB-INF/views/profile/../include/top.jsp(113,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberType eq 'member'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
              if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item active\"><a\r\n");
                  out.write("\t\t\t\t\t\t\t\t\thref=\"");
                  out.print(request.getContextPath());
                  out.write("/member/mypage_M.do\"\r\n");
                  out.write("\t\t\t\t\t\t\t\t\tclass=\"nav-link\">MyPage</a></li>\r\n");
                  out.write("\t\t\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
              _jspx_th_c_005fif_005f1_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t");
            //  c:if
            org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
            boolean _jspx_th_c_005fif_005f2_reused = false;
            try {
              _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
              // /WEB-INF/views/profile/../include/top.jsp(118,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberType eq 'trainer'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
              if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item active\"><a\r\n");
                  out.write("\t\t\t\t\t\t\t\t\thref=\"");
                  out.print(request.getContextPath());
                  out.write("/member/mypage_T.do\"\r\n");
                  out.write("\t\t\t\t\t\t\t\t\tclass=\"nav-link\">MyPage</a></li>\r\n");
                  out.write("\t\t\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
              _jspx_th_c_005fif_005f2_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t");
            //  c:if
            org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
            boolean _jspx_th_c_005fif_005f3_reused = false;
            try {
              _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
              // /WEB-INF/views/profile/../include/top.jsp(123,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberType eq 'manager'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
              if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t\t\t\t<li class=\"nav-item active\"><a\r\n");
                  out.write("\t\t\t\t\t\t\t\t\thref=\"");
                  out.print(request.getContextPath());
                  out.write("/manager/report.do\"\r\n");
                  out.write("\t\t\t\t\t\t\t\t\tclass=\"nav-link\">Manager</a></li>\r\n");
                  out.write("\t\t\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
              _jspx_th_c_005fif_005f3_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item active\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/index/aboutus.do\" class=\"nav-link\">AboutUs</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item active\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/matching/main.do\" class=\"nav-link\">Matching</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item active\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/notice/notice.do?start=1&end=5\" class=\"nav-link\">Notice</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"topWrapper\" id=\"topWrapper\"\r\n");
      out.write("\t\t\tstyle=\"position: absolute; top: 1vw; right: 1vw;\">\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f5_reused = false;
      try {
        _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f5.setParent(null);
        // /WEB-INF/views/profile/../include/top.jsp(152,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
        if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t<div class=\"topLogOut\">\r\n");
            out.write("\t\t\t\t");
            //  c:if
            org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
            boolean _jspx_th_c_005fif_005f6_reused = false;
            try {
              _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
              _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f5);
              // /WEB-INF/views/profile/../include/top.jsp(154,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberType eq 'member'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
              if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t<a style=\"color:black\" href=\"");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("/message/msgboxrecv.do\">✉</a>\r\n");
                  out.write("\t\t\t\t\t<a onclick=\"location= 'detail.cs?id=");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write('"');
                  out.write('>');
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("\t님  환영합니다. </a>\r\n");
                  out.write("\t\t\t\t\t<a href =\"");
                  out.print(request.getContextPath());
                  out.write("/member/mypage_M.do\"> /  myPage</a>\r\n");
                  out.write("\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
              _jspx_th_c_005fif_005f6_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
            }
            out.write("\r\n");
            out.write("\t\t\t\t");
            if (_jspx_meth_c_005fif_005f7(_jspx_th_c_005fif_005f5, _jspx_page_context))
              return;
            out.write("\t\r\n");
            out.write("\t\t\t\t\t\t<!-- <a>MyPage</a>  -->\r\n");
            out.write("\t\t\t\t\t\t<a href=\"");
            out.print(request.getContextPath());
            out.write("/member/logout.do\">/  logout</a>\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
        _jspx_th_c_005fif_005f5_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인모달  -->\r\n");
      out.write("<div class=\"modal fade\" id=\"loginModal\" tabindex=\"-1\" role=\"dialog\" >\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("        <!-- 닫기버튼 -->\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <form class=\"form-signin\" action=\"");
      out.print(request.getContextPath());
      out.write("/member/loginImple.do\">\r\n");
      out.write("            <h2 id=\"title\">Please sign in</h2>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 offset-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"toggle_radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"toggle_option\" id=\"first_toggle\"\tname=\"account\" value=\"member\"checked> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"radio\" class=\"toggle_option\" id=\"second_toggle\" name=\"account\" value=\"trainer\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t <label for=\"first_toggle\"><p>Member</p></label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"second_toggle\"><p>Trainer</p></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"toggle_option_slider\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("            \r\n");
      out.write("            <label for=\"userEmail\" class=\"sr-only\">Email address</label>\r\n");
      out.write("            <input type=\"text\" id=\"email\" name=\"email\" class=\"form-control\" placeholder=\"Email address\" required autofocus>\r\n");
      out.write("            <label for=\"userPwd\" class=\"sr-only\">Password</label>\r\n");
      out.write("            <input type=\"password\" name=\"password\" id=\"password\" class=\"form-control\" placeholder=\"Password\" required>\r\n");
      out.write("            <div class=\"warning\"></div>\r\n");
      out.write("            <button class=\"btn btn-lg btn-primary btn-block\" id=\"btnLogin\" type=\"submit\">로그인</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <a type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</a>\r\n");
      out.write("        <a type=\"button\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/find_pw_form.do\" class=\"btn btn-primary\"> 비밀번호 찾기 </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 가입모달 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"joinModal\" tabindex=\"-1\" role=\"dialog\" >\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("      \t<h3 id=\"headerTitle\">Welcome Teu-Ching!</h3>\r\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("        <!-- 닫기버튼 -->\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <p id=\"Jointitle\">만나서 반갑습니다! <br>가입하실 유형을 선택해주세요.</p>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-group row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 offset-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"toggle_radio\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"first_toggle\"><a id=\"atag\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/mjoin.do?data=member\">Member</a></label> \r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"second_toggle\"><a id=\"atag\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/mjoin.do?data=trainer\"> Trainer</a></label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <a type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write(" <script src=\"../resources/js/account/login.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 시작 시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작시작 -->\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"hero-wrap hero-wrap-2\"\r\n");
      out.write("\t\tstyle=\"background-image: url('../resources/img/bg_3.jpg');\"\r\n");
      out.write("\t\tdata-stellar-background-ratio=\"0.5\">\r\n");
      out.write("\t\t<div class=\"overlay\"></div>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div\r\n");
      out.write("\t\t\t\tclass=\"row no-gutters slider-text js-fullheight align-items-center justify-content-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-9 ftco-animate text-center\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"mb-3 bread\">S C H E D U L E</h1>\r\n");
      out.write("\t\t\t\t\t<p class=\"breadcrumbs\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"mr-2\">Trainer</span> <span>Schedule</span>\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ftco-section\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center mb-8 pb-6\">\r\n");
      out.write("\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t<p id=\"sctitle\">예약은 해당 트레이너와 쪽지 후 최종 매칭이 가능합니다.</p>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table table-bordered text-center\" border=\"1\" style=\"table-layout: fixed\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 이전달, 다음달 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#a\" id=\"prev\"> 이전달 <i class=\"ion-ios-arrow-round-back\"></i></a>\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\" id=\"current-year-month\" colspan=\"5\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#a\" id=\"next\"> 다음달 <i class=\"ion-ios-arrow-round-forward\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 요일 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"bg-primary text-white\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Sun</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Mon</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Tue</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Wed</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Thu</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Fri</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Sat</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tbody id=\"calendar-body\" class=\"calendar-body\"></tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<form id=\"form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/message/matchform.do\" target=\"pop\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"year\" value=\"\" name=\"year\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"month\" value=\"\" name=\"month\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"date\" value=\"\" name=\"date\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"date\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tr_email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"tr_email\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t  \r\n");
      out.write("\t  var currentTitle = document.getElementById('current-year-month');\r\n");
      out.write("\t  /* 현재 년도와 월 */\r\n");
      out.write("\t\tvar calendarBody = document.getElementById('calendar-body');\r\n");
      out.write("\t\tvar mainTodayDay = document.getElementById('main-day');\r\n");
      out.write("\t\tvar mainTodayDate = document.getElementById('main-date');\r\n");
      out.write("\t  \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* Date객체를 사용하여 오늘의 날짜, 연도, 요일등의 정보를 담기. */\r\n");
      out.write("\t\tvar today = new Date();\r\n");
      out.write("\t\tvar first = new Date(today.getFullYear(), today.getMonth(),1);\r\n");
      out.write("\t\tvar dayList = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];\r\n");
      out.write("\t\tvar monthList = ['1','2','3','4','5','6','7','8','9','10','11','12'];\r\n");
      out.write("\t\tvar leapYear=[31,29,31,30,31,30,31,31,30,31,30,31];\r\n");
      out.write("\t\tvar notLeapYear=[31,28,31,30,31,30,31,31,30,31,30,31];\r\n");
      out.write("\t\tvar pageFirst = first;\r\n");
      out.write("\t\tvar pageYear;\r\n");
      out.write("\t\tvar date = today.getDate();\r\n");
      out.write("\t\tvar month = today.getMonth()+1;\r\n");
      out.write("\t\tvar year = today.getFullYear();\r\n");
      out.write("\t\tvar nextyear = today.getFullYear()+1;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(first.getFullYear() % 4 === 0){\r\n");
      out.write("\t\t\t/* 윤년을 체크하기 위한 IF문. 윤년일 경우  leapYear 배열을 pageYear에 담고 */\r\n");
      out.write("\t\t    pageYear = leapYear;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t/* 아닐 경우 notLeapYear배열을 pageYear에 담는다.  */\r\n");
      out.write("\t\t    pageYear = notLeapYear;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* 이렇게 되면 leapYear, notLeapYear 배열에는 각각 1월부터 12월까지의 총 일수가 들어가있게 됨. */\r\n");
      out.write("\r\n");
      out.write("\t\tfunction showCalendar(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t    let monthCnt = 100;\r\n");
      out.write("\t\t    let cnt = 1;\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    for(var i = 0; i < 6; i++){\r\n");
      out.write("\t\t    \t/* 주(week)를 만들기 (최대 6주니까!)*/\r\n");
      out.write("\t\t        var $tr = document.createElement('tr');\r\n");
      out.write("\t\t    \t/* 그 6주에 해당하는 tr요소 생성하기. */\r\n");
      out.write("\t\t        $tr.setAttribute('id', monthCnt);   \r\n");
      out.write("\t\t    \t/* tr(주)의 id에 '월' 로 속성주기 */\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        for(var j = 0; j < 7; j++){\r\n");
      out.write("\t\t        \t/* 일(date)를 만들기 (일주일은 최대 7일이니까) */\r\n");
      out.write("\t\t            if((i === 0 && j < first.getDay()) || cnt > pageYear[first.getMonth()]){\r\n");
      out.write("\t\t            \t/* 만약 첫번째 주라면 시작하는 요일부터 출력을 해야해. \r\n");
      out.write("\t\t            \t|| 달력 출력 종료 조건. 월마다 총 일수가 다르니까 pageYear에 담아논 총 월마다의 일수와 비교하여 날짜를 출력. */\r\n");
      out.write("\t\t                var $td = document.createElement('td');\r\n");
      out.write("\t\t            \t/* td로 생성된 요소를 $td로 담아  */\r\n");
      out.write("\t\t                $tr.appendChild($td);\r\n");
      out.write("\t\t            \t/* 아까 주에서 추가할때 썼던 $tr에 appendChild 해주기. */\r\n");
      out.write("\t\t            \t$td.setAttribute('class','text-center');\r\n");
      out.write("\t\t            \t$td.style.wordBreak=\"break-all\";\r\n");
      out.write("\t\t            }else{\r\n");
      out.write("\t\t            \t/* 만약 첫번째 주가 아니라면(2,3,4,5,6...) */\r\n");
      out.write("\t\t                var $td = document.createElement('td');\r\n");
      out.write("\t\t                $td.innerHTML = \"<p>\"+cnt + \"</p>\";\r\n");
      out.write("\t\t                /* td 변수에 날짜를 text로 넣기!! */\r\n");
      out.write("\t\t                $td.setAttribute('id', cnt);     \r\n");
      out.write("\t\t                /* $td(일)의 id값을 cnt로 주기 */\r\n");
      out.write("\t\t                $tr.appendChild($td);\r\n");
      out.write("\t\t                /* tr(주) 밑에 td(일) appendChild하기 */\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                $td.setAttribute('class','text-center');\r\n");
      out.write("\t\t            \t$td.style.wordBreak=\"break-all\";\r\n");
      out.write("\t\t            \t\r\n");
      out.write("\t\t            \t\r\n");
      out.write("\t\t            \tvar $at = document.createElement('a');\r\n");
      out.write("\t\t            \tvar $pt = document.createElement('a');\r\n");
      out.write("\t\t            \tconsole.log(nextyear);\r\n");
      out.write("\t\t            \t\r\n");
      out.write("\t\t            \t\r\n");
      out.write("\t\t            \t\r\n");
      out.write("\t\t            \t/* 예약하기 버튼 생성 */\r\n");
      out.write("\t\t            \t$td.appendChild($at);\r\n");
      out.write("\t\t            \t$at.innerHTML = \"예약하기\";\r\n");
      out.write("\t\t            \t$at.setAttribute('href','#a');\r\n");
      out.write("\t\t\t            $at.setAttribute('class','reply');\r\n");
      out.write("\t\t            \t\r\n");
      out.write("\t\t            \t\t\r\n");
      out.write("\t\t            \t\t\r\n");
      out.write("\t\t            \t\r\n");
      out.write("\t\t\t            /*  */\r\n");
      out.write("\t\t\t            $at.setAttribute('id', \"day\");\r\n");
      out.write("\t\t\t            $at.setAttribute('data-date', cnt);\r\n");
      out.write("\t\t\t            $at.onclick = click;\r\n");
      out.write("\t\t\t            $pt.onclick = noclick;\r\n");
      out.write("\t\t\t            /*  */\r\n");
      out.write("\t\t                cnt++;\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t        monthCnt++;\r\n");
      out.write("\t\t        /* 월이 for문 도는동안 계속 증가하게. */\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t        calendarBody.appendChild($tr);\r\n");
      out.write("\t\t        /* calendarBody 태그 밑에 tr(주) appendChild 하기 */\r\n");
      out.write("\t\t        currentTitle.innerHTML = first.getFullYear() + '&nbsp;&nbsp;&nbsp;&nbsp;'+ monthList[first.getMonth()];\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tshowCalendar();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar clickedDate1 = document.getElementById(today.getDate());\r\n");
      out.write("\t\tclickedDate1.classList.add('active');\r\n");
      out.write("\t\tvar prevBtn = document.getElementById('prev');\r\n");
      out.write("\t\tvar nextBtn = document.getElementById('next');\r\n");
      out.write("\t\tprevBtn.addEventListener('click',prev);\r\n");
      out.write("\t\tnextBtn.addEventListener('click',next);\r\n");
      out.write("\t\tvar tdGroup = [];\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tfunction removeCalendar(){\r\n");
      out.write("\t\t\t/* 추후 달력 업데이를 위해 미리 만들어놓는  부분  */\r\n");
      out.write("\t\t    let catchTr = 100;\r\n");
      out.write("\t\t    for(var i = 100; i< 106; i++){\r\n");
      out.write("\t\t        var $tr = document.getElementById(catchTr);\r\n");
      out.write("\t\t        $tr.remove();\r\n");
      out.write("\t\t        catchTr++;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction clickStart(){\r\n");
      out.write("\t\t    for(let i = 1; i <= pageYear[first.getMonth()]; i++){\r\n");
      out.write("\t\t        tdGroup[i] = document.getElementById(i);\r\n");
      out.write("\t\t        tdGroup[i].addEventListener('click',changeToday);\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction changeToday(e){\r\n");
      out.write("\t\t    for(let i = 1; i <= pageYear[first.getMonth()]; i++){\r\n");
      out.write("\t\t        if(tdGroup[i].classList.contains('active')){\r\n");
      out.write("\t\t            tdGroup[i].classList.remove('active');\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    clickedDate1 = e.currentTarget;\r\n");
      out.write("\t\t    clickedDate1.classList.add('active');\r\n");
      out.write("\t\t    today = new Date(today.getFullYear(), today.getMonth(), clickedDate1.id);\r\n");
      out.write("\t\t    keyValue = today.getFullYear() + '' + today.getMonth()+ '' + today.getDate();\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction prev(){\r\n");
      out.write("\t\t\t/* 이전 달로 이동하는 함수 */\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t    \t/* pageFirst(월 첫번째 날에 대한 정보가 담겨있는 변수) 와 \r\n");
      out.write("\t\t\t   pageYear(월 마다의 총 일수)를 업데이트 할거야.\r\n");
      out.write("\t\t\t   (넘기기 전의 데이터들을 삭제하는 과정)*/\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t    if(pageFirst.getMonth() === 1){\r\n");
      out.write("\t\t    \t/* 만약 1월이라면 연도를 변경해야 함 */\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t        pageFirst = new Date(first.getFullYear()-1, 12, 1);\r\n");
      out.write("\t\t    \t/* 월 첫번째 날을 작년도의 12월 1일정보로 가져오기 */\r\n");
      out.write("\t\t        first = pageFirst;\r\n");
      out.write("\t\t    \t/* first에 전년도 12월 1일을 담아서  */\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t        if(first.getFullYear() % 4 === 0){\r\n");
      out.write("\t\t        \t/* 윤달이면 leapYear */\r\n");
      out.write("\t\t            pageYear = leapYear;\r\n");
      out.write("\t\t        }else{\r\n");
      out.write("\t\t        \t/* 윤달이 아니면 notLeapYear */\r\n");
      out.write("\t\t            pageYear = notLeapYear;\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    }else{\r\n");
      out.write("\t\t    \t/* 12월이여도 연도를 변경해야돼. */\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t        pageFirst = new Date(first.getFullYear(), first.getMonth()-1, 1);\r\n");
      out.write("\t\t    \t/* 내년의 1월 1일을 가져오게. */\r\n");
      out.write("\t\t        first = pageFirst;\r\n");
      out.write("\t\t        /* first에 내년의 1월 1일을 담아  */\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    today = new Date(today.getFullYear(), today.getMonth()-1, today.getDate());\r\n");
      out.write("\t\t    /* today에 해당하는 Date를 담아서 */\r\n");
      out.write("\t\t    currentTitle.innerHTML = first.getFullYear() + '&nbsp;&nbsp;&nbsp;&nbsp;'+ monthList[first.getMonth()];\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    removeCalendar();\r\n");
      out.write("\t\t    showCalendar();\r\n");
      out.write("\t\t    /* 다시 showCalendar함수를 호출해서 달력 불러 */\r\n");
      out.write("\t\t    clickedDate1 = document.getElementById(today.getDate());\r\n");
      out.write("\t\t    clickedDate1.classList.add('active');\r\n");
      out.write("\t\t    clickStart();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tfunction next(){\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t    if(pageFirst.getMonth() === 12){\r\n");
      out.write("\t\t        pageFirst = new Date(first.getFullYear()+1, 1, 1);\r\n");
      out.write("\t\t        first = pageFirst;\r\n");
      out.write("\t\t        if(first.getFullYear() % 4 === 0){\r\n");
      out.write("\t\t            pageYear = leapYear;\r\n");
      out.write("\t\t        }else{\r\n");
      out.write("\t\t            pageYear = notLeapYear;\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    }else{\r\n");
      out.write("\t\t        pageFirst = new Date(first.getFullYear(), first.getMonth()+1, 1);\r\n");
      out.write("\t\t        first = pageFirst;\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    today = new Date(today.getFullYear(), today.getMonth() + 1, today.getDate());\r\n");
      out.write("\t\t    currentTitle.innerHTML = first.getFullYear() + '&nbsp;&nbsp;&nbsp;&nbsp;'+ monthList[first.getMonth()];\r\n");
      out.write("\t\t    removeCalendar();\r\n");
      out.write("\t\t    showCalendar(); \r\n");
      out.write("\t\t    clickedDate1 = document.getElementById(today.getDate());\r\n");
      out.write("\t\t    clickedDate1.classList.add('active');  \r\n");
      out.write("\t\t    clickStart();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t  \r\n");
      out.write("\t  /* 트레이너 상담신청시 띄울 팝업용 */\r\n");
      out.write("\t  function openPopUp() {\r\n");
      out.write("\t\t\tconst form = document.querySelector('#form');\r\n");
      out.write("\t\t\twindow.open(\"\", 'pop',\r\n");
      out.write("\t\t\t\t\t\t\t'width=450,height=400,left=420,top=150,toolbars=no,scrollbars=no');\r\n");
      out.write("\t\t\tform.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t  \r\n");
      out.write("\t   \r\n");
      out.write("\t   \tfunction click(e){\r\n");
      out.write("\t   \t\tlet month_year = $('#current-year-month').text();\r\n");
      out.write("\t\t \tlet click_year = month_year.substring(0,4);\r\n");
      out.write("\t\t\tlet click_month = month_year.substring(8);\r\n");
      out.write("\t\t\tlet click_date = e.target.dataset.date;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t$('#year').val(click_year);\r\n");
      out.write("\t\t\t$('#month').val(click_month);\r\n");
      out.write("\t\t\t$('#date').val(click_date);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t   \t\t\t/* openPopUp(); */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t   \t\t\r\n");
      out.write("\t   \t\tif((year > click_year) || (year == click_year && month > click_month) || \r\n");
      out.write("\t   \t\t\t\t(year == click_year && month == click_month && date > click_date)){\r\n");
      out.write("\t   \t\t\tnoclick();\r\n");
      out.write("\t   \t\t}else{\r\n");
      out.write("\t   \t\t\topenPopUp();\r\n");
      out.write("\t   \t\t}\r\n");
      out.write("\t   \t\t\r\n");
      out.write("\t   \t}\r\n");
      out.write("\t   \t\r\n");
      out.write("\t   \tfunction noclick() {\r\n");
      out.write("\t\t\talert(\"이전 날짜에는 예약이 불가합니다.\")\r\n");
      out.write("\t\t}\r\n");
      out.write("\t  \r\n");
      out.write("\t \r\n");
      out.write("\t</script>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<footer class=\"ftco-footer ftco-section bg-light\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row d-flex\">\r\n");
      out.write("\t\t\t<div class=\"col-md\">\r\n");
      out.write("\t\t\t\t<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"ftco-heading-2\">Meditative</h2>\r\n");
      out.write("\t\t\t\t\t<p>Far far away, behind the word mountains, far from the\r\n");
      out.write("\t\t\t\t\t\tcountries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("\t\t\t\t\t<ul class=\"ftco-footer-social list-unstyled float-lft mt-3\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-twitter\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-facebook\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"icon-instagram\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md\">\r\n");
      out.write("\t\t\t\t<div class=\"ftco-footer-widget mb-4 ml-md-4\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"ftco-heading-2\">Popular Links</h2>\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/teuching/matching/main.do\">Matching</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md\">\r\n");
      out.write("\t\t\t\t<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"ftco-heading-2\">Quick Links</h2>\r\n");
      out.write("\t\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/index/index.do\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/index/aboutus.do\">About</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/notice/notice.do?start=1&end=5\">Notice</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md\">\r\n");
      out.write("\t\t\t\t<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("\t\t\t\t\t<h2 class=\"ftco-heading-2\">Have a Questions?</h2>\r\n");
      out.write("\t\t\t\t\t<div class=\"block-23 mb-3\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><span class=\"icon icon-map-marker\"></span><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text\">6 Teheran-ro 14-gil, Gangnam-gu, Seoul</span></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"icon icon-phone\"></span><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"text\">1544-9970</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"text\">teuching.official@gmail.com</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p class=\"mb-0\">\r\n");
      out.write("\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\t\t\t\t\tCopyright &copy;\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\tdocument.write(new Date().getFullYear());\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\tAll rights reserved | This template is made with <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"icon-heart\" aria-hidden=\"true\"></i> by <a\r\n");
      out.write("\t\t\t\t\t\thref=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("\t\t\t\t\t<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"ftco-loader\" class=\"show fullscreen\">\r\n");
      out.write("\t\t<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("\t\t\t<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("\t\t\t\tstroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("\t\t\t<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("\t\t\t\tstroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\t<script src=\"../resources/js/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/popper.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/aos.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/scrollax.min.js\"></script>\r\n");
      out.write("\t<script src=\"../resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/profile/../include/top.jsp(145,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<!-- 로그인  -->\r\n");
          out.write("\t\t\t\t<div class=\"topLogin\">\r\n");
          out.write("\t\t\t\t\t<a id=\"btnModal\" href=\"#\">Login / </a>\r\n");
          out.write("\t\t\t\t\t <a id=\"btnJModal\" href=\"#\"> Join</a>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f5, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f5);
      // /WEB-INF/views/profile/../include/top.jsp(159,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberType eq 'trainer'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<a style=\"color:black\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/profile/reviewforTR.do?trainerEmail=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.tr_email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">🇲🇵</a>\r\n");
          out.write("\t\t\t\t\t<a style=\"color:black\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/message/msgboxrecv.do\">✉</a>\r\n");
          out.write("\t\t\t\t\t<a onclick=\"location= 'detail.cs?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.trainerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginInfo.trainerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\t님  환영합니다. </a>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }
}
