/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-06-20 15:38:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinform_005fT_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Teu-Ching Teu-Ching</title>\r\n");
      out.write("<style>\r\n");
      out.write("input::placeholder {\r\n");
      out.write("\tcolor: gray;\r\n");
      out.write("\tfont-size: small;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("\tbackground-image: url(../resources/img/tr4.jpg) !important;\r\n");
      out.write("\t-webkit-background-size: cover;\r\n");
      out.write("\t-moz-background-size: cover;\r\n");
      out.write("\t-o-background-size: cover;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("\toverflow-x: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-color: transparent !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#imagePreview {\r\n");
      out.write("\twidth: 240px;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\toverflow: hidden !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- 카카오지도 -->\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=42e0be41ec144283c6bfe7c0ed8dae35&libraries=services\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"main-content\">\r\n");
      out.write("\t\t<div class=\"container mt-7\">\r\n");
      out.write("\t\t\t<!-- Table -->\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xl-8 m-auto order-xl-1\" style=\"margin-top: 5% !important; margin-bottom: 4% !important;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card bg-secondary shadow\" style=\"background-color: #f8f9fe !important;\">\r\n");
      out.write("\t\t\t\t\t<form id=\"signFrm\" name=\"signFrm\"\r\n");
      out.write("\t\t\t\t\t  action=\"");
      out.print(request.getContextPath());
      out.write("/member/t_joinemailCheck.do\" \r\n");
      out.write("\t       \t\t\t\t\tmethod=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-header bg-white border-0\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"mb-0\">트칭 트레이너 회원가입</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-4 text-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" id=\"signUp\" class=\"btn btn-sm btn-primary\">가입하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"heading-small text-muted mb-4\">User information</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pl-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-control-label\">Email 주소</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" id=\"check_email\" style=\"font-size: small;\">중복확인</button><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"email\" id=\"email\" name=\"email\" maxlength=\"50\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control form-control-alternative\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"작성하신 주소로 인증메일이 발송됩니다.\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle= \"font-size: small; width:100%; height:30px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"emailChk\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group focused\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-control-label\">비밀번호\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label> <input type=\"password\" id=\"password_1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"password\" class=\"pw\" maxlength=\"20\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"display: block; width: 100%; padding: .375rem .75rem; font-size: 1rem; line-height: 1.5; color: #495057; background-color: #fff; background-clip: padding-box; border: 1px solid #ced4da; border-radius: .25rem; transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group focused\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-control-label\">비밀번호 확인</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" id=\"password_2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"pw\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"display: block; width: 100%; padding: .375rem .75rem; font-size: 1rem; line-height: 1.5; color: #495057; background-color: #fff; background-clip: padding-box; border: 1px solid #ced4da; border-radius: .25rem; transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span id=\"alert-success\" style=\"display: none;\">비밀번호가 일치합니다.</span>\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t<span id=\"alert-danger\" style=\"display: none; color: #d92742; font-weight: bold; \">\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t비밀번호가 일치하지 않습니다.</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group focused\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-control-label\">성함 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label> <input type=\"text\" id=\"name\" name=\"name\" maxlength=\"20\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control form-control-alternative\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group focused\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-control-label\">성별\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control form-control-alternative\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: small;\" name=\"gender\" id=\"gender\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option>남성</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option>여성</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group focused\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-control-label\">신장 (cm)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label> <input type=\"text\" id=\"height\" name=\"height\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control form-control-alternative\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"HEIGHT\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group focused\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-control-label\">체중 (kg)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label> <input type=\"text\" id=\"weight\" name=\"weight\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control form-control-alternative\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"WEIGHT\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr class=\"my-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Address -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"heading-small text-muted mb-4\">Contact\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinformation</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pl-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group focused\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-control-label\">연락처 <br><span style=\"font-size: small;\">붙임표(-)까지 입력해주세요.</span></span></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"cell\" name=\"cell\" maxlength=\"13\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control form-control-alternative\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group focused\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-control-label\" for=\"input-address\">트레이닝 가능 장소 주소 입력</label><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"sample6_postcode\" placeholder=\"우편번호\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" onclick=\"sample6_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-control-label\" for=\"input-address\"></label><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"sample6_address\" placeholder=\"주소\" name=\"address\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:55%; height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-control-label\" for=\"input-address\"></label><br><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"sample6_detailAddress\" placeholder=\"상세주소\" name=\"address_detail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-control-label\" for=\"input-address\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"sample6_extraAddress\" placeholder=\"참고항목\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<hr class=\"my-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- Description -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6 class=\"heading-small text-muted mb-4\">About Me</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"pl-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group focused\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-control-label\">프로필 사진 등록</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"imagePreview\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<img id=\"img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"file\" id=\"photo\" accept=\"image/*\" onchange=\"setThumbnail(event);\" name=\"file\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"pl-lg-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group focused\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label>트레이너님을 소개하는 인사말과 커리어</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<textarea class=\"form-control form-control-alternative\" cols=\"80\" rows=\"10\" id=\"career\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"트레이너님을 나타낼 수 있는 정보와 커리어를 자유롭게 작성해 주세요.\" name=\"career\"></textarea>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span style=\"color:#aaa;\" id=\"counter\">(0 / 최대 500자)</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group focused\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"form-control-label\" for=\"input-address\">선호 지역 선택하기</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t지역 1 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"prefer1-1\" id=\"sido1\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"prefer1-2\" id=\"gugun1\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t지역 2 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"prefer2-1\" id=\"sido2\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"prefer2-2\" id=\"gugun2\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t지역 3 \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"prefer3-1\" id=\"sido3\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select name=\"prefer3-2\" id=\"gugun3\"></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"../resources/js/account/join_T.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
